POST http://localhost:8080/api/form/contact HTTP/1.1
content-type: application/json

{
    "fname": "Jake De",
    "lname": "Workerb",
    "phone": "231-381-9812",
    "email": "b.clincy@gmail.com",
    "token": "T0hKUE1FeFBiR3haWVdaQ01sZFBMMkZ3VUVaTlRuSmhaREp6TlhGUlMwZDNkbkZYUVdwWlozSTFXamcyYmt0UVozaHFPU3RxYVd4M1pXWmhkbmxCTDNSTFUxVXlORzVVUzNCeVlVeGlWVGRxZVZWdWNXOWtXR2RQUm1kWWVFaGpkMlZvWkdNMmQyZENURUZsZDNwbkt6bFZMMk5FTlZab1FtSTJMMWxwZUZKaWVHVXpWWGhaTjFndlF6ZFNXR2RVZVN0RGNuaDNQVDA9Ond5THZlWWtaYnoyR0tpakE=",
    "message": "I am interested in volunteering. Please contact me.",
    "hoursAvailable": 14,
    "times": "{{$timestamp}}"
}
