GET http://localhost:8080/api/form/strDecode.php?token=T0hKUE1FeFBiR3haWVdaQ01sZFBMMkZ3VUVaTlRuSmhaREp6TlhGUlMwZDNkbkZYUVdwWlozSTFXamcyYmt0UVozaHFPU3RxYVd4M1pXWmhkbmxCTDNSTFUxVXlORzVVUzNCeVlVeGlWVGRxZVZWdWNXOWtXR2RQUm1kWWVFaGpkMlZvWkdNMmQyZENURUZsZDNwbkt6bFZMMk5FTlZab1FtSTJMMWxwZUZKaWVHVXpWWGhaTjFndlF6ZFNXR2RVZVN0RGNuaDNQVDA9Ond5THZlWWtaYnoyR0tpakE= HTTP/1.1
content-type: application/json
